version: '3.7' 

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  node:
    image: node:18.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    entrypoint: node
    working_dir: /home/node
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - .:/home/node
  
  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080

volumes:
  db-data: {}