version: '3.7' 

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  node:
    image: node:18.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    entrypoint: node
    working_dir: /home/node
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/chatbot
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - .:/home/node
  
  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8081:8080

volumes:
  db-data: {}